In [37]:
import numpy as np
import pandas as pd

In [38]:
d1=pd.DataFrame({
    "key":["a","b","c","c","d","e"],
    "num1":range(6)
})
d2=pd.DataFrame({
    "key":["b","c","e","f"],
    "num2":range(4)
})


In [39]:
# merge the dataframe
pd.merge(d1,d2)

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [40]:
pd.merge(d1,d2,on="key")

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [41]:
d3=pd.DataFrame({
    "key1":["a","b","c","c","d","e"],
    "num1":range(6)
})
d4=pd.DataFrame({
    "key2":["b","c","e","f"],
    "num2":range(4)
})
d3,d4

(  key1  num1
 0    a     0
 1    b     1
 2    c     2
 3    c     3
 4    d     4
 5    e     5,
   key2  num2
 0    b     0
 1    c     1
 2    e     2
 3    f     3)

In [42]:
pd.merge(d3,d4,left_on="key1",right_on="key2")

key1  num1 key2  num2
0    b     1    b     0
1    c     2    c     1
2    c     3    c     1
3    e     5    e     2

In [43]:
pd.merge(d1,d2,how="outer")

key  num1  num2
0   a   0.0   NaN
1   b   1.0   0.0
2   c   2.0   1.0
3   c   3.0   1.0
4   d   4.0   NaN
5   e   5.0   2.0
6   f   NaN   3.0

In [44]:
pd.merge(d1,d2,how="left")          #takes the left table intact

key  num1  num2
0   a     0   NaN
1   b     1   0.0
2   c     2   1.0
3   c     3   1.0
4   d     4   NaN
5   e     5   2.0

In [45]:
pd.merge(d1,d2)         #how=inner is default
    

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [46]:
pd.merge(d1,d2,how="right")     #takes the right table intact


key  num1  num2
0   b   1.0     0
1   c   2.0     1
2   c   3.0     1
3   e   5.0     2
4   f   NaN     3

In [47]:
pd.merge(d1,d2,how="inner")     #merges most Common part, inner is default

key  num1  num2
0   b     1     0
1   c     2     1
2   c     3     1
3   e     5     2

In [48]:
df1=pd.DataFrame({
    "key1":["a","b","c","c","d","e"],
    "num1":range(6),
    "count":["one","two","three","four","five","six"]
})
df2=pd.DataFrame({
    "key2":["b","c","e","f"],
    "num2":range(4),
    "count":["one","two","three","four",]

})

In [49]:
df1,df2

(  key1  num1  count
 0    a     0    one
 1    b     1    two
 2    c     2  three
 3    c     3   four
 4    d     4   five
 5    e     5    six,
   key2  num2  count
 0    b     0    one
 1    c     1    two
 2    e     2  three
 3    f     3   four)

In [70]:
dataf=pd.DataFrame(
    [[1,2],[2,3],[4,5]],
    index=["a","b","f"],
    columns=["Alex","Keta"]
)

In [72]:
dataf

Alex  Keta
a     1     2
b     2     3
f     4     5

In [75]:
#join function

In [79]:
seq=np.arange(20).reshape(4,5)
seq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
np.concatenate([seq,seq],axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [86]:
np.concatenate([seq,seq],axis=0)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [98]:
data1=pd.Series([0,1],index=["c","d"])
data2=pd.Series(range(2,5,1),index=["c","d","e"])
data3=pd.Series(range(5,7,1),index=["f","g"])
data1,data2,data3

(c    0
 d    1
 dtype: int64,
 c    2
 d    3
 e    4
 dtype: int64,
 f    5
 g    6
 dtype: int64)

In [99]:
pd.concat([data1,data2,data3])  # how=innner

c    0
d    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [100]:
pd.concat([data1,data2,data3],axis=1)

0    1    2
c  0.0  2.0  NaN
d  1.0  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [102]:
data4=pd.Series(range(10,13,1),index=["a","b","c"])
data4


a    10
b    11
c    12
dtype: int64

In [110]:
pd.concat([data1,data4],join="inner",axis=1)

0   1
c  0  12

In [120]:
x=pd.concat([data1,data2,data4],keys=["one","two","three"])

In [121]:
x

one    c     0
       d     1
two    c     2
       d     3
       e     4
three  a    10
       b    11
       c    12
dtype: int64

In [128]:
data1=pd.DataFrame(np.random.randn(3,4).reshape(3,4),columns=['a','b','c','d'])
data1

a         b         c         d
0 -1.624887 -0.607316  0.677299  0.867579
1 -0.140630 -0.252631 -0.051729  0.239583
2 -0.301409 -0.035273  0.551389 -0.135533

In [129]:
data2=pd.DataFrame(np.random.randn(2,3).reshape(2,3),columns=['b','d','a'])
data2


b         d         a
0  1.492426  2.056872  0.899558
1 -1.256899  1.194804  0.438551

In [131]:
pd.concat([data1,data2])

a         b         c         d
0 -1.624887 -0.607316  0.677299  0.867579
1 -0.140630 -0.252631 -0.051729  0.239583
2 -0.301409 -0.035273  0.551389 -0.135533
0  0.899558  1.492426       NaN  2.056872
1  0.438551 -1.256899       NaN  1.194804

In [134]:
pd.concat([data1,data2],ignore_index=True)

a         b         c         d
0 -1.624887 -0.607316  0.677299  0.867579
1 -0.140630 -0.252631 -0.051729  0.239583
2 -0.301409 -0.035273  0.551389 -0.135533
3  0.899558  1.492426       NaN  2.056872
4  0.438551 -1.256899       NaN  1.194804

In [135]:
from nycflights13 import flights
from nycflights13 import airlines
from nycflights13 import airports

In [141]:
flights.head(10)

year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0  2013      1    1     517.0             515        2.0     830.0   
1  2013      1    1     533.0             529        4.0     850.0   
2  2013      1    1     542.0             540        2.0     923.0   
3  2013      1    1     544.0             545       -1.0    1004.0   
4  2013      1    1     554.0             600       -6.0     812.0   
5  2013      1    1     554.0             558       -4.0     740.0   
6  2013      1    1     555.0             600       -5.0     913.0   
7  2013      1    1     557.0             600       -3.0     709.0   
8  2013      1    1     557.0             600       -3.0     838.0   
9  2013      1    1     558.0             600       -2.0     753.0   

   sched_arr_time  arr_delay carrier  flight tailnum origin dest  air_time  \
0             819       11.0      UA    1545  N14228    EWR  IAH     227.0   
1             830       20.0      UA    1714  N24211    LGA  IAH     227.0   
2             850       33.0      AA    1141  N619AA    JFK  MIA     160.0   
3            1022      -18.0      B6     725  N804JB    JFK  BQN     183.0   
4             837      -25.0      DL     461  N668DN    LGA  ATL     116.0   
5             728       12.0      UA    1696  N39463    EWR  ORD     150.0   
6             854       19.0      B6     507  N516JB    EWR  FLL     158.0   
7             723      -14.0      EV    5708  N829AS    LGA  IAD      53.0   
8             846       -8.0      B6      79  N593JB    JFK  MCO     140.0   
9             745        8.0      AA     301  N3ALAA    LGA  ORD     138.0   

   distance  hour  minute             time_hour  
0      1400     5      15  2013-01-01T10:00:00Z  
1      1416     5      29  2013-01-01T10:00:00Z  
2      1089     5      40  2013-01-01T10:00:00Z  
3      1576     5      45  2013-01-01T10:00:00Z  
4       762     6       0  2013-01-01T11:00:00Z  
5       719     5      58  2013-01-01T10:00:00Z  
6      1065     6       0  2013-01-01T11:00:00Z  
7       229     6       0  2013-01-01T11:00:00Z  
8       944     6       0  2013-01-01T11:00:00Z  
9       733     6       0  2013-01-01T11:00:00Z

In [142]:
airlines.head(10)

carrier                         name
0      9E            Endeavor Air Inc.
1      AA       American Airlines Inc.
2      AS         Alaska Airlines Inc.
3      B6              JetBlue Airways
4      DL         Delta Air Lines Inc.
5      EV     ExpressJet Airlines Inc.
6      F9       Frontier Airlines Inc.
7      FL  AirTran Airways Corporation
8      HA       Hawaiian Airlines Inc.
9      MQ                    Envoy Air

In [143]:
airports.head(10)

faa                            name        lat         lon   alt  tz dst  \
0  04G               Lansdowne Airport  41.130472  -80.619583  1044  -5   A   
1  06A   Moton Field Municipal Airport  32.460572  -85.680028   264  -6   A   
2  06C             Schaumburg Regional  41.989341  -88.101243   801  -6   A   
3  06N                 Randall Airport  41.431912  -74.391561   523  -5   A   
4  09J           Jekyll Island Airport  31.074472  -81.427778    11  -5   A   
5  0A9  Elizabethton Municipal Airport  36.371222  -82.173417  1593  -5   A   
6  0G6         Williams County Airport  41.467306  -84.506778   730  -5   A   
7  0G7   Finger Lakes Regional Airport  42.883565  -76.781232   492  -5   A   
8  0P2    Shoestring Aviation Airfield  39.794824  -76.647191  1000  -5   U   
9  0S9           Jefferson County Intl  48.053809 -122.810644   108  -8   A   

                 tzone  
0     America/New_York  
1      America/Chicago  
2      America/Chicago  
3     America/New_York  
4     America/New_York  
5     America/New_York  
6     America/New_York  
7     America/New_York  
8     America/New_York  
9  America/Los_Angeles

In [144]:
delay_flights=flights[flights["dep_delay"]>0].groupby('carrier').size().reset_index(name='num_delay')

In [145]:
delay_flights

carrier  num_delay
0       9E       7063
1       AA      10162
2       AS        226
3       B6      21445
4       DL      15241
5       EV      23139
6       F9        341
7       FL       1654
8       HA         69
9       MQ       8031
10      OO          9
11      UA      27261
12      US       4775
13      VX       2225
14      WN       6558
15      YV        233

In [154]:
delay_flights=delay_flights.merge(airlines,on="carrier",how="left")
delay_flights

carrier  num_delay                       name_x  \
0       9E       7063            Endeavor Air Inc.   
1       AA      10162       American Airlines Inc.   
2       AS        226         Alaska Airlines Inc.   
3       B6      21445              JetBlue Airways   
4       DL      15241         Delta Air Lines Inc.   
5       EV      23139     ExpressJet Airlines Inc.   
6       F9        341       Frontier Airlines Inc.   
7       FL       1654  AirTran Airways Corporation   
8       HA         69       Hawaiian Airlines Inc.   
9       MQ       8031                    Envoy Air   
10      OO          9        SkyWest Airlines Inc.   
11      UA      27261        United Air Lines Inc.   
12      US       4775              US Airways Inc.   
13      VX       2225               Virgin America   
14      WN       6558       Southwest Airlines Co.   
15      YV        233           Mesa Airlines Inc.   

                         name_y  
0             Endeavor Air Inc.  
1        American Airlines Inc.  
2          Alaska Airlines Inc.  
3               JetBlue Airways  
4          Delta Air Lines Inc.  
5      ExpressJet Airlines Inc.  
6        Frontier Airlines Inc.  
7   AirTran Airways Corporation  
8        Hawaiian Airlines Inc.  
9                     Envoy Air  
10        SkyWest Airlines Inc.  
11        United Air Lines Inc.  
12              US Airways Inc.  
13               Virgin America  
14       Southwest Airlines Co.  
15           Mesa Airlines Inc.

In [166]:
delay_flights['num_delay'].max()

27261

In [169]:
flights.groupby('dest').agg(mean_delay=("arr_delay","mean"))

mean_delay
dest            
ABQ     4.381890
ACK     4.852273
ALB    14.397129
ANC    -2.500000
ATL    11.300113
...          ...
TPA     7.408525
TUL    33.659864
TVC    12.968421
TYS    24.069204
XNA     7.465726

[105 rows x 1 columns]

In [172]:
flights.groupby('dest').agg(mean_delay=('arr_delay', 'mean')).reset_index()\
    .query('mean_delay == mean_delay.min()').merge(airports, left_on='dest', right_on='faa', how='left')

dest  mean_delay  faa        name      lat        lon  alt  tz dst  \
0  LEX       -22.0  LEX  Blue Grass  38.0365 -84.605889  979  -5   A   

              tzone  
0  America/New_York

In [173]:
flights.groupby('dest').agg(mean_delay=('arr_delay', 'mean')).reset_index()\
    .query('mean_delay == mean_delay.min()')\
    .merge(airports, left_on='dest', right_on='faa')\
    .loc[:, ['name']]

name
0  Blue Grass